DROP USER tbweb CASCADE;

DROP TABLESPACE tbweb INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE tbweb
  DATAFILE '/home/oracle/tbweb/tbweb.dbf' SIZE 100M
  AUTOEXTEND ON NEXT 100M
  LOGGING
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO ;

CREATE USER tbweb PROFILE DEFAULT IDENTIFIED BY tbweb DEFAULT TABLESPACE tbweb ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE, CREATE VIEW TO tbweb;